#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insert_Tilbud(_Tilbud instance);
  partial void Update_Tilbud(_Tilbud instance);
  partial void Delete_Tilbud(_Tilbud instance);
  partial void Insert_Bruger(_Bruger instance);
  partial void Update_Bruger(_Bruger instance);
  partial void Delete_Bruger(_Bruger instance);
  partial void Insert_Indhold(_Indhold instance);
  partial void Update_Indhold(_Indhold instance);
  partial void Delete_Indhold(_Indhold instance);
  partial void Insert_Kategori(_Kategori instance);
  partial void Update_Kategori(_Kategori instance);
  partial void Delete_Kategori(_Kategori instance);
  partial void Insert_Kontaktoplysninger(_Kontaktoplysninger instance);
  partial void Update_Kontaktoplysninger(_Kontaktoplysninger instance);
  partial void Delete_Kontaktoplysninger(_Kontaktoplysninger instance);
  partial void Insert_Mearke(_Mearke instance);
  partial void Update_Mearke(_Mearke instance);
  partial void Delete_Mearke(_Mearke instance);
  partial void Insert_Nyhed(_Nyhed instance);
  partial void Update_Nyhed(_Nyhed instance);
  partial void Delete_Nyhed(_Nyhed instance);
  partial void Insert_Billede(_Billede instance);
  partial void Update_Billede(_Billede instance);
  partial void Delete_Billede(_Billede instance);
  partial void Insert_Produkt(_Produkt instance);
  partial void Update_Produkt(_Produkt instance);
  partial void Delete_Produkt(_Produkt instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<_Tilbud> _Tilbuds
	{
		get
		{
			return this.GetTable<_Tilbud>();
		}
	}
	
	public System.Data.Linq.Table<_Bruger> _Brugers
	{
		get
		{
			return this.GetTable<_Bruger>();
		}
	}
	
	public System.Data.Linq.Table<_Indhold> _Indholds
	{
		get
		{
			return this.GetTable<_Indhold>();
		}
	}
	
	public System.Data.Linq.Table<_Kategori> _Kategoris
	{
		get
		{
			return this.GetTable<_Kategori>();
		}
	}
	
	public System.Data.Linq.Table<_Kontaktoplysninger> _Kontaktoplysningers
	{
		get
		{
			return this.GetTable<_Kontaktoplysninger>();
		}
	}
	
	public System.Data.Linq.Table<_Mearke> _Mearkes
	{
		get
		{
			return this.GetTable<_Mearke>();
		}
	}
	
	public System.Data.Linq.Table<_Nyhed> _Nyheds
	{
		get
		{
			return this.GetTable<_Nyhed>();
		}
	}
	
	public System.Data.Linq.Table<_Billede> _Billedes
	{
		get
		{
			return this.GetTable<_Billede>();
		}
	}
	
	public System.Data.Linq.Table<_Produkt> _Produkts
	{
		get
		{
			return this.GetTable<_Produkt>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Tilbud]")]
public partial class _Tilbud : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _tilbud_id;
	
	private decimal _tilbud_pris;
	
	private int _fk_prod_id;
	
	private System.DateTime _startdato;
	
	private System.DateTime _slutdato;
	
	private EntityRef<_Produkt> @__Produkt;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontilbud_idChanging(int value);
    partial void Ontilbud_idChanged();
    partial void Ontilbud_prisChanging(decimal value);
    partial void Ontilbud_prisChanged();
    partial void Onfk_prod_idChanging(int value);
    partial void Onfk_prod_idChanged();
    partial void OnstartdatoChanging(System.DateTime value);
    partial void OnstartdatoChanged();
    partial void OnslutdatoChanging(System.DateTime value);
    partial void OnslutdatoChanged();
    #endregion
	
	public _Tilbud()
	{
		this.@__Produkt = default(EntityRef<_Produkt>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tilbud_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int tilbud_id
	{
		get
		{
			return this._tilbud_id;
		}
		set
		{
			if ((this._tilbud_id != value))
			{
				this.Ontilbud_idChanging(value);
				this.SendPropertyChanging();
				this._tilbud_id = value;
				this.SendPropertyChanged("tilbud_id");
				this.Ontilbud_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tilbud_pris", DbType="Decimal(18,0) NOT NULL")]
	public decimal tilbud_pris
	{
		get
		{
			return this._tilbud_pris;
		}
		set
		{
			if ((this._tilbud_pris != value))
			{
				this.Ontilbud_prisChanging(value);
				this.SendPropertyChanging();
				this._tilbud_pris = value;
				this.SendPropertyChanged("tilbud_pris");
				this.Ontilbud_prisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_prod_id", DbType="Int NOT NULL")]
	public int fk_prod_id
	{
		get
		{
			return this._fk_prod_id;
		}
		set
		{
			if ((this._fk_prod_id != value))
			{
				if (this.@__Produkt.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_prod_idChanging(value);
				this.SendPropertyChanging();
				this._fk_prod_id = value;
				this.SendPropertyChanged("fk_prod_id");
				this.Onfk_prod_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdato", DbType="DateTime2 NOT NULL")]
	public System.DateTime startdato
	{
		get
		{
			return this._startdato;
		}
		set
		{
			if ((this._startdato != value))
			{
				this.OnstartdatoChanging(value);
				this.SendPropertyChanging();
				this._startdato = value;
				this.SendPropertyChanged("startdato");
				this.OnstartdatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slutdato", DbType="DateTime2 NOT NULL")]
	public System.DateTime slutdato
	{
		get
		{
			return this._slutdato;
		}
		set
		{
			if ((this._slutdato != value))
			{
				this.OnslutdatoChanging(value);
				this.SendPropertyChanging();
				this._slutdato = value;
				this.SendPropertyChanged("slutdato");
				this.OnslutdatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Produkt__Tilbud", Storage="__Produkt", ThisKey="fk_prod_id", OtherKey="id", IsForeignKey=true)]
	public _Produkt _Produkt
	{
		get
		{
			return this.@__Produkt.Entity;
		}
		set
		{
			_Produkt previousValue = this.@__Produkt.Entity;
			if (((previousValue != value) 
						|| (this.@__Produkt.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Produkt.Entity = null;
					previousValue._Tilbuds.Remove(this);
				}
				this.@__Produkt.Entity = value;
				if ((value != null))
				{
					value._Tilbuds.Add(this);
					this._fk_prod_id = value.id;
				}
				else
				{
					this._fk_prod_id = default(int);
				}
				this.SendPropertyChanged("_Produkt");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Bruger]")]
public partial class _Bruger : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _bruger_id;
	
	private string _password;
	
	private string _brugernavn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbruger_idChanging(int value);
    partial void Onbruger_idChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnbrugernavnChanging(string value);
    partial void OnbrugernavnChanged();
    #endregion
	
	public _Bruger()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bruger_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int bruger_id
	{
		get
		{
			return this._bruger_id;
		}
		set
		{
			if ((this._bruger_id != value))
			{
				this.Onbruger_idChanging(value);
				this.SendPropertyChanging();
				this._bruger_id = value;
				this.SendPropertyChanged("bruger_id");
				this.Onbruger_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brugernavn", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string brugernavn
	{
		get
		{
			return this._brugernavn;
		}
		set
		{
			if ((this._brugernavn != value))
			{
				this.OnbrugernavnChanging(value);
				this.SendPropertyChanging();
				this._brugernavn = value;
				this.SendPropertyChanged("brugernavn");
				this.OnbrugernavnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Indhold]")]
public partial class _Indhold : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _tekst;
	
	private int _fk_billede_id;
	
	private EntityRef<_Billede> @__Billede;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntekstChanging(string value);
    partial void OntekstChanged();
    partial void Onfk_billede_idChanging(int value);
    partial void Onfk_billede_idChanged();
    #endregion
	
	public _Indhold()
	{
		this.@__Billede = default(EntityRef<_Billede>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string tekst
	{
		get
		{
			return this._tekst;
		}
		set
		{
			if ((this._tekst != value))
			{
				this.OntekstChanging(value);
				this.SendPropertyChanging();
				this._tekst = value;
				this.SendPropertyChanged("tekst");
				this.OntekstChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_billede_id", DbType="Int NOT NULL")]
	public int fk_billede_id
	{
		get
		{
			return this._fk_billede_id;
		}
		set
		{
			if ((this._fk_billede_id != value))
			{
				if (this.@__Billede.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_billede_idChanging(value);
				this.SendPropertyChanging();
				this._fk_billede_id = value;
				this.SendPropertyChanged("fk_billede_id");
				this.Onfk_billede_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Indhold", Storage="__Billede", ThisKey="fk_billede_id", OtherKey="billede_id", IsForeignKey=true)]
	public _Billede _Billede
	{
		get
		{
			return this.@__Billede.Entity;
		}
		set
		{
			_Billede previousValue = this.@__Billede.Entity;
			if (((previousValue != value) 
						|| (this.@__Billede.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Billede.Entity = null;
					previousValue._Indholds.Remove(this);
				}
				this.@__Billede.Entity = value;
				if ((value != null))
				{
					value._Indholds.Add(this);
					this._fk_billede_id = value.billede_id;
				}
				else
				{
					this._fk_billede_id = default(int);
				}
				this.SendPropertyChanged("_Billede");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Kategori]")]
public partial class _Kategori : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _kategori_id;
	
	private string _kategori_navn;
	
	private EntitySet<_Mearke> @__Mearkes;
	
	private EntitySet<_Produkt> @__Produkts;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkategori_idChanging(int value);
    partial void Onkategori_idChanged();
    partial void Onkategori_navnChanging(string value);
    partial void Onkategori_navnChanged();
    #endregion
	
	public _Kategori()
	{
		this.@__Mearkes = new EntitySet<_Mearke>(new Action<_Mearke>(this.attach__Mearkes), new Action<_Mearke>(this.detach__Mearkes));
		this.@__Produkts = new EntitySet<_Produkt>(new Action<_Produkt>(this.attach__Produkts), new Action<_Produkt>(this.detach__Produkts));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int kategori_id
	{
		get
		{
			return this._kategori_id;
		}
		set
		{
			if ((this._kategori_id != value))
			{
				this.Onkategori_idChanging(value);
				this.SendPropertyChanging();
				this._kategori_id = value;
				this.SendPropertyChanged("kategori_id");
				this.Onkategori_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori_navn", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string kategori_navn
	{
		get
		{
			return this._kategori_navn;
		}
		set
		{
			if ((this._kategori_navn != value))
			{
				this.Onkategori_navnChanging(value);
				this.SendPropertyChanging();
				this._kategori_navn = value;
				this.SendPropertyChanged("kategori_navn");
				this.Onkategori_navnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Kategori__Mearke", Storage="__Mearkes", ThisKey="kategori_id", OtherKey="fk_kategori_id")]
	public EntitySet<_Mearke> _Mearkes
	{
		get
		{
			return this.@__Mearkes;
		}
		set
		{
			this.@__Mearkes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Kategori__Produkt", Storage="__Produkts", ThisKey="kategori_id", OtherKey="fk_kategori_id")]
	public EntitySet<_Produkt> _Produkts
	{
		get
		{
			return this.@__Produkts;
		}
		set
		{
			this.@__Produkts.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Mearkes(_Mearke entity)
	{
		this.SendPropertyChanging();
		entity._Kategori = this;
	}
	
	private void detach__Mearkes(_Mearke entity)
	{
		this.SendPropertyChanging();
		entity._Kategori = null;
	}
	
	private void attach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Kategori = this;
	}
	
	private void detach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Kategori = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Kontaktoplysninger]")]
public partial class _Kontaktoplysninger : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _navn;
	
	private int _postnr;
	
	private string _byen;
	
	private string _adresse;
	
	private string _telefon;
	
	private string _email;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnavnChanging(string value);
    partial void OnnavnChanged();
    partial void OnpostnrChanging(int value);
    partial void OnpostnrChanged();
    partial void OnbyenChanging(string value);
    partial void OnbyenChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public _Kontaktoplysninger()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_navn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string navn
	{
		get
		{
			return this._navn;
		}
		set
		{
			if ((this._navn != value))
			{
				this.OnnavnChanging(value);
				this.SendPropertyChanging();
				this._navn = value;
				this.SendPropertyChanged("navn");
				this.OnnavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postnr", DbType="Int NOT NULL")]
	public int postnr
	{
		get
		{
			return this._postnr;
		}
		set
		{
			if ((this._postnr != value))
			{
				this.OnpostnrChanging(value);
				this.SendPropertyChanging();
				this._postnr = value;
				this.SendPropertyChanged("postnr");
				this.OnpostnrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string byen
	{
		get
		{
			return this._byen;
		}
		set
		{
			if ((this._byen != value))
			{
				this.OnbyenChanging(value);
				this.SendPropertyChanging();
				this._byen = value;
				this.SendPropertyChanged("byen");
				this.OnbyenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string adresse
	{
		get
		{
			return this._adresse;
		}
		set
		{
			if ((this._adresse != value))
			{
				this.OnadresseChanging(value);
				this.SendPropertyChanging();
				this._adresse = value;
				this.SendPropertyChanged("adresse");
				this.OnadresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string telefon
	{
		get
		{
			return this._telefon;
		}
		set
		{
			if ((this._telefon != value))
			{
				this.OntelefonChanging(value);
				this.SendPropertyChanging();
				this._telefon = value;
				this.SendPropertyChanged("telefon");
				this.OntelefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Mearke]")]
public partial class _Mearke : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _mearke_id;
	
	private string _mearke_navn;
	
	private int _fk_billede_id;
	
	private string _mearke_beskrivelse;
	
	private int _fk_kategori_id;
	
	private EntitySet<_Produkt> @__Produkts;
	
	private EntityRef<_Kategori> @__Kategori;
	
	private EntityRef<_Billede> @__Billede;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmearke_idChanging(int value);
    partial void Onmearke_idChanged();
    partial void Onmearke_navnChanging(string value);
    partial void Onmearke_navnChanged();
    partial void Onfk_billede_idChanging(int value);
    partial void Onfk_billede_idChanged();
    partial void Onmearke_beskrivelseChanging(string value);
    partial void Onmearke_beskrivelseChanged();
    partial void Onfk_kategori_idChanging(int value);
    partial void Onfk_kategori_idChanged();
    #endregion
	
	public _Mearke()
	{
		this.@__Produkts = new EntitySet<_Produkt>(new Action<_Produkt>(this.attach__Produkts), new Action<_Produkt>(this.detach__Produkts));
		this.@__Kategori = default(EntityRef<_Kategori>);
		this.@__Billede = default(EntityRef<_Billede>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mearke_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int mearke_id
	{
		get
		{
			return this._mearke_id;
		}
		set
		{
			if ((this._mearke_id != value))
			{
				this.Onmearke_idChanging(value);
				this.SendPropertyChanging();
				this._mearke_id = value;
				this.SendPropertyChanged("mearke_id");
				this.Onmearke_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mearke_navn", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string mearke_navn
	{
		get
		{
			return this._mearke_navn;
		}
		set
		{
			if ((this._mearke_navn != value))
			{
				this.Onmearke_navnChanging(value);
				this.SendPropertyChanging();
				this._mearke_navn = value;
				this.SendPropertyChanged("mearke_navn");
				this.Onmearke_navnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_billede_id", DbType="Int NOT NULL")]
	public int fk_billede_id
	{
		get
		{
			return this._fk_billede_id;
		}
		set
		{
			if ((this._fk_billede_id != value))
			{
				if (this.@__Billede.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_billede_idChanging(value);
				this.SendPropertyChanging();
				this._fk_billede_id = value;
				this.SendPropertyChanged("fk_billede_id");
				this.Onfk_billede_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mearke_beskrivelse", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string mearke_beskrivelse
	{
		get
		{
			return this._mearke_beskrivelse;
		}
		set
		{
			if ((this._mearke_beskrivelse != value))
			{
				this.Onmearke_beskrivelseChanging(value);
				this.SendPropertyChanging();
				this._mearke_beskrivelse = value;
				this.SendPropertyChanged("mearke_beskrivelse");
				this.Onmearke_beskrivelseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_kategori_id", DbType="Int NOT NULL")]
	public int fk_kategori_id
	{
		get
		{
			return this._fk_kategori_id;
		}
		set
		{
			if ((this._fk_kategori_id != value))
			{
				if (this.@__Kategori.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_kategori_idChanging(value);
				this.SendPropertyChanging();
				this._fk_kategori_id = value;
				this.SendPropertyChanged("fk_kategori_id");
				this.Onfk_kategori_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Mearke__Produkt", Storage="__Produkts", ThisKey="mearke_id", OtherKey="fk_mearke_id")]
	public EntitySet<_Produkt> _Produkts
	{
		get
		{
			return this.@__Produkts;
		}
		set
		{
			this.@__Produkts.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Kategori__Mearke", Storage="__Kategori", ThisKey="fk_kategori_id", OtherKey="kategori_id", IsForeignKey=true)]
	public _Kategori _Kategori
	{
		get
		{
			return this.@__Kategori.Entity;
		}
		set
		{
			_Kategori previousValue = this.@__Kategori.Entity;
			if (((previousValue != value) 
						|| (this.@__Kategori.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Kategori.Entity = null;
					previousValue._Mearkes.Remove(this);
				}
				this.@__Kategori.Entity = value;
				if ((value != null))
				{
					value._Mearkes.Add(this);
					this._fk_kategori_id = value.kategori_id;
				}
				else
				{
					this._fk_kategori_id = default(int);
				}
				this.SendPropertyChanged("_Kategori");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Mearke", Storage="__Billede", ThisKey="fk_billede_id", OtherKey="billede_id", IsForeignKey=true)]
	public _Billede _Billede
	{
		get
		{
			return this.@__Billede.Entity;
		}
		set
		{
			_Billede previousValue = this.@__Billede.Entity;
			if (((previousValue != value) 
						|| (this.@__Billede.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Billede.Entity = null;
					previousValue._Mearkes.Remove(this);
				}
				this.@__Billede.Entity = value;
				if ((value != null))
				{
					value._Mearkes.Add(this);
					this._fk_billede_id = value.billede_id;
				}
				else
				{
					this._fk_billede_id = default(int);
				}
				this.SendPropertyChanged("_Billede");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Mearke = this;
	}
	
	private void detach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Mearke = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Nyhed]")]
public partial class _Nyhed : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _nyhed_id;
	
	private string _overskrift;
	
	private string _tekst;
	
	private System.DateTime _dato;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnyhed_idChanging(int value);
    partial void Onnyhed_idChanged();
    partial void OnoverskriftChanging(string value);
    partial void OnoverskriftChanged();
    partial void OntekstChanging(string value);
    partial void OntekstChanged();
    partial void OndatoChanging(System.DateTime value);
    partial void OndatoChanged();
    #endregion
	
	public _Nyhed()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nyhed_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int nyhed_id
	{
		get
		{
			return this._nyhed_id;
		}
		set
		{
			if ((this._nyhed_id != value))
			{
				this.Onnyhed_idChanging(value);
				this.SendPropertyChanging();
				this._nyhed_id = value;
				this.SendPropertyChanged("nyhed_id");
				this.Onnyhed_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overskrift", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string overskrift
	{
		get
		{
			return this._overskrift;
		}
		set
		{
			if ((this._overskrift != value))
			{
				this.OnoverskriftChanging(value);
				this.SendPropertyChanging();
				this._overskrift = value;
				this.SendPropertyChanged("overskrift");
				this.OnoverskriftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekst", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string tekst
	{
		get
		{
			return this._tekst;
		}
		set
		{
			if ((this._tekst != value))
			{
				this.OntekstChanging(value);
				this.SendPropertyChanging();
				this._tekst = value;
				this.SendPropertyChanged("tekst");
				this.OntekstChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dato", DbType="DateTime2 NOT NULL")]
	public System.DateTime dato
	{
		get
		{
			return this._dato;
		}
		set
		{
			if ((this._dato != value))
			{
				this.OndatoChanging(value);
				this.SendPropertyChanging();
				this._dato = value;
				this.SendPropertyChanged("dato");
				this.OndatoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Billede]")]
public partial class _Billede : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _billede_id;
	
	private string _billede_navn;
	
	private EntitySet<_Indhold> @__Indholds;
	
	private EntitySet<_Mearke> @__Mearkes;
	
	private EntitySet<_Produkt> @__Produkts;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbillede_idChanging(int value);
    partial void Onbillede_idChanged();
    partial void Onbillede_navnChanging(string value);
    partial void Onbillede_navnChanged();
    #endregion
	
	public _Billede()
	{
		this.@__Indholds = new EntitySet<_Indhold>(new Action<_Indhold>(this.attach__Indholds), new Action<_Indhold>(this.detach__Indholds));
		this.@__Mearkes = new EntitySet<_Mearke>(new Action<_Mearke>(this.attach__Mearkes), new Action<_Mearke>(this.detach__Mearkes));
		this.@__Produkts = new EntitySet<_Produkt>(new Action<_Produkt>(this.attach__Produkts), new Action<_Produkt>(this.detach__Produkts));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billede_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int billede_id
	{
		get
		{
			return this._billede_id;
		}
		set
		{
			if ((this._billede_id != value))
			{
				this.Onbillede_idChanging(value);
				this.SendPropertyChanging();
				this._billede_id = value;
				this.SendPropertyChanged("billede_id");
				this.Onbillede_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_billede_navn", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string billede_navn
	{
		get
		{
			return this._billede_navn;
		}
		set
		{
			if ((this._billede_navn != value))
			{
				this.Onbillede_navnChanging(value);
				this.SendPropertyChanging();
				this._billede_navn = value;
				this.SendPropertyChanged("billede_navn");
				this.Onbillede_navnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Indhold", Storage="__Indholds", ThisKey="billede_id", OtherKey="fk_billede_id")]
	public EntitySet<_Indhold> _Indholds
	{
		get
		{
			return this.@__Indholds;
		}
		set
		{
			this.@__Indholds.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Mearke", Storage="__Mearkes", ThisKey="billede_id", OtherKey="fk_billede_id")]
	public EntitySet<_Mearke> _Mearkes
	{
		get
		{
			return this.@__Mearkes;
		}
		set
		{
			this.@__Mearkes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Produkt", Storage="__Produkts", ThisKey="billede_id", OtherKey="fk_billede_id")]
	public EntitySet<_Produkt> _Produkts
	{
		get
		{
			return this.@__Produkts;
		}
		set
		{
			this.@__Produkts.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Indholds(_Indhold entity)
	{
		this.SendPropertyChanging();
		entity._Billede = this;
	}
	
	private void detach__Indholds(_Indhold entity)
	{
		this.SendPropertyChanging();
		entity._Billede = null;
	}
	
	private void attach__Mearkes(_Mearke entity)
	{
		this.SendPropertyChanging();
		entity._Billede = this;
	}
	
	private void detach__Mearkes(_Mearke entity)
	{
		this.SendPropertyChanging();
		entity._Billede = null;
	}
	
	private void attach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Billede = this;
	}
	
	private void detach__Produkts(_Produkt entity)
	{
		this.SendPropertyChanging();
		entity._Billede = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Produkt]")]
public partial class _Produkt : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _model;
	
	private decimal _pris;
	
	private string _beskrivelse;
	
	private int _fk_kategori_id;
	
	private int _fk_mearke_id;
	
	private System.Nullable<int> _fk_billede_id;
	
	private string _produktdetaljer;
	
	private EntitySet<_Tilbud> @__Tilbuds;
	
	private EntityRef<_Billede> @__Billede;
	
	private EntityRef<_Kategori> @__Kategori;
	
	private EntityRef<_Mearke> @__Mearke;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnprisChanging(decimal value);
    partial void OnprisChanged();
    partial void OnbeskrivelseChanging(string value);
    partial void OnbeskrivelseChanged();
    partial void Onfk_kategori_idChanging(int value);
    partial void Onfk_kategori_idChanged();
    partial void Onfk_mearke_idChanging(int value);
    partial void Onfk_mearke_idChanged();
    partial void Onfk_billede_idChanging(System.Nullable<int> value);
    partial void Onfk_billede_idChanged();
    partial void OnproduktdetaljerChanging(string value);
    partial void OnproduktdetaljerChanged();
    #endregion
	
	public _Produkt()
	{
		this.@__Tilbuds = new EntitySet<_Tilbud>(new Action<_Tilbud>(this.attach__Tilbuds), new Action<_Tilbud>(this.detach__Tilbuds));
		this.@__Billede = default(EntityRef<_Billede>);
		this.@__Kategori = default(EntityRef<_Kategori>);
		this.@__Mearke = default(EntityRef<_Mearke>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string model
	{
		get
		{
			return this._model;
		}
		set
		{
			if ((this._model != value))
			{
				this.OnmodelChanging(value);
				this.SendPropertyChanging();
				this._model = value;
				this.SendPropertyChanged("model");
				this.OnmodelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pris", DbType="Decimal(18,0) NOT NULL")]
	public decimal pris
	{
		get
		{
			return this._pris;
		}
		set
		{
			if ((this._pris != value))
			{
				this.OnprisChanging(value);
				this.SendPropertyChanging();
				this._pris = value;
				this.SendPropertyChanged("pris");
				this.OnprisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beskrivelse", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string beskrivelse
	{
		get
		{
			return this._beskrivelse;
		}
		set
		{
			if ((this._beskrivelse != value))
			{
				this.OnbeskrivelseChanging(value);
				this.SendPropertyChanging();
				this._beskrivelse = value;
				this.SendPropertyChanged("beskrivelse");
				this.OnbeskrivelseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_kategori_id", DbType="Int NOT NULL")]
	public int fk_kategori_id
	{
		get
		{
			return this._fk_kategori_id;
		}
		set
		{
			if ((this._fk_kategori_id != value))
			{
				if (this.@__Kategori.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_kategori_idChanging(value);
				this.SendPropertyChanging();
				this._fk_kategori_id = value;
				this.SendPropertyChanged("fk_kategori_id");
				this.Onfk_kategori_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_mearke_id", DbType="Int NOT NULL")]
	public int fk_mearke_id
	{
		get
		{
			return this._fk_mearke_id;
		}
		set
		{
			if ((this._fk_mearke_id != value))
			{
				if (this.@__Mearke.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_mearke_idChanging(value);
				this.SendPropertyChanging();
				this._fk_mearke_id = value;
				this.SendPropertyChanged("fk_mearke_id");
				this.Onfk_mearke_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_billede_id", DbType="Int")]
	public System.Nullable<int> fk_billede_id
	{
		get
		{
			return this._fk_billede_id;
		}
		set
		{
			if ((this._fk_billede_id != value))
			{
				if (this.@__Billede.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_billede_idChanging(value);
				this.SendPropertyChanging();
				this._fk_billede_id = value;
				this.SendPropertyChanged("fk_billede_id");
				this.Onfk_billede_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produktdetaljer", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string produktdetaljer
	{
		get
		{
			return this._produktdetaljer;
		}
		set
		{
			if ((this._produktdetaljer != value))
			{
				this.OnproduktdetaljerChanging(value);
				this.SendPropertyChanging();
				this._produktdetaljer = value;
				this.SendPropertyChanged("produktdetaljer");
				this.OnproduktdetaljerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Produkt__Tilbud", Storage="__Tilbuds", ThisKey="id", OtherKey="fk_prod_id")]
	public EntitySet<_Tilbud> _Tilbuds
	{
		get
		{
			return this.@__Tilbuds;
		}
		set
		{
			this.@__Tilbuds.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Billede__Produkt", Storage="__Billede", ThisKey="fk_billede_id", OtherKey="billede_id", IsForeignKey=true)]
	public _Billede _Billede
	{
		get
		{
			return this.@__Billede.Entity;
		}
		set
		{
			_Billede previousValue = this.@__Billede.Entity;
			if (((previousValue != value) 
						|| (this.@__Billede.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Billede.Entity = null;
					previousValue._Produkts.Remove(this);
				}
				this.@__Billede.Entity = value;
				if ((value != null))
				{
					value._Produkts.Add(this);
					this._fk_billede_id = value.billede_id;
				}
				else
				{
					this._fk_billede_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("_Billede");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Kategori__Produkt", Storage="__Kategori", ThisKey="fk_kategori_id", OtherKey="kategori_id", IsForeignKey=true)]
	public _Kategori _Kategori
	{
		get
		{
			return this.@__Kategori.Entity;
		}
		set
		{
			_Kategori previousValue = this.@__Kategori.Entity;
			if (((previousValue != value) 
						|| (this.@__Kategori.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Kategori.Entity = null;
					previousValue._Produkts.Remove(this);
				}
				this.@__Kategori.Entity = value;
				if ((value != null))
				{
					value._Produkts.Add(this);
					this._fk_kategori_id = value.kategori_id;
				}
				else
				{
					this._fk_kategori_id = default(int);
				}
				this.SendPropertyChanged("_Kategori");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_Mearke__Produkt", Storage="__Mearke", ThisKey="fk_mearke_id", OtherKey="mearke_id", IsForeignKey=true)]
	public _Mearke _Mearke
	{
		get
		{
			return this.@__Mearke.Entity;
		}
		set
		{
			_Mearke previousValue = this.@__Mearke.Entity;
			if (((previousValue != value) 
						|| (this.@__Mearke.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this.@__Mearke.Entity = null;
					previousValue._Produkts.Remove(this);
				}
				this.@__Mearke.Entity = value;
				if ((value != null))
				{
					value._Produkts.Add(this);
					this._fk_mearke_id = value.mearke_id;
				}
				else
				{
					this._fk_mearke_id = default(int);
				}
				this.SendPropertyChanged("_Mearke");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach__Tilbuds(_Tilbud entity)
	{
		this.SendPropertyChanging();
		entity._Produkt = this;
	}
	
	private void detach__Tilbuds(_Tilbud entity)
	{
		this.SendPropertyChanging();
		entity._Produkt = null;
	}
}
#pragma warning restore 1591
